apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: mohammaddocker/k8s-tuto-product-api
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: MONGO_URI
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: JWT_KEY
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: PORT
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"


---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000