apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mohammaddocker/k8s-tuto-user-api
          imagePullPolicy: Always
          env:
            - name: PG_URI
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: PG_URI
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: JWT_KEY
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: PORT
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
