apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: mohammaddocker/k8s-tuto-product-api
          imagePullPolicy: Always
          env:
            - name: MONGO_URI
              value: mongodb://root:QRVZTS2VYA@mgo-mongodb.default.svc.cluster.local:27017/
            - name: JWT_KEY
              value: your-jwt-key
            - name: PORT
              value: '3000'
            - name: USER_API_URL
              value: http://user:3000/api/v1/
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: "0.5"
