apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mohammaddocker/k8s-tuto-user-api
          imagePullPolicy: Always
          env:
            - name: PG_URI
              value: postgres://postgres:uSUpwxHWiF@pg-postgresql.default.svc.cluster.local:5432/
            - name: JWT_KEY
              value: your-jwt-key
            - name: PORT
              value: '3000'
            - name: CLIENT_URL
              value: http://localhost:3003/
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: 512Mi
              cpu: "0.5"
            requests:
              memory: 512Mi
              cpu: "0.5"

---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
